apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: auto-pe-rw-job-boundary-caller
on:
  workflow_dispatch:
    
jobs:
  call-reusable:
    uses: .cloudbees/workflows/auto-pe-rw-job-boundary.yaml

  independent-job:
    steps:
      - name: Independent step
        uses: docker://alpine:3.19
        shell: sh
        run: echo "independent job"

  post-rw-job:
    needs:
      - call-reusable
    steps:
      - name: Post-RW step
        uses: docker://alpine:3.19
        shell: sh
        run: echo "dependent job"
